#!/bin/bash

if [[ $# -eq 0 ]] ; then
    echo 'You need to specify a book to build'
    echo 'ex: build drupal'
    echo 'Available books\n'
    ls book_*.json | sed -e 's/^book_(.*)\.json$/ccc/g'
    exit 0
fi
export BOOK=$1
# echo "{\"name\":\"$BOOK\", \"title\":`cat book_$BOOK.json | jq '.title'`}," >> ./_books/index.txt
#gitbook install
gitbook build
rm -rf  _books/$1
mkdir -p _books/$1
cp -r _book/* _books/$1/
