name: 'search'

type: 'python:3.10'

variables:
    env:
        MEILISEARCH_VERSION: '0.30.1'
        POETRY_VERSION: '1.3.2'
        POETRY_VIRTUALENVS_IN_PROJECT: true
        POETRY_VIRTUALENVS_CREATE: false

dependencies:
    python3:
        pipx: 1.1.0

hooks:
    build: !include
        type: string
        path: build.sh
    post_deploy:
        bash ./post_deploy.sh

web:
    commands:
      # Run the Meilisearch server
      start: !include
            type: string
            path: start.sh

# The size of the persistent disk of the application (in MB).
disk: 2048

crons:
    indexExternalSites:
        # Run at 06:00 UTC every day
        spec: '0 6 * * *'
        commands:
            start: !include
                type: string
                path: index_external_sites.sh

mounts:
    "data.ms":
        source: local
        source_path: "datams"
    "output":
        source: local
        source_path: "output"
    "data":
        source: local
        source_path: "data"
    "dumps":
        source: local
        source_path: "dumps"
