blank_issues_enabled: false # Force people to start from a template
contact_links:
  - name: "Upsun Support - open a Support ticket" 
    url: https://console.upsun.com/-/users/~/tickets/open
    about: If you're experiencing problems with the Upsun Flex or Fixed product offerings, please open a Support ticket.
  - name: "Upsun Community Forum - questions and messages"
    url: https://community.upsun.com
    about: For questions and discussion about Upsun Flex or Upsun Fixed product offerings, reach out on the Upsun Community Forum!
