name: Improvements
description: For changes to improve existing Upsun Flex and Upsun Fixed content.
labels:
  - ungroomed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in helping improve the Upsun docs!
        Please fill in the fields below so we can understand what changes are needed.

  - type: textarea
    attributes:
      label: Where should the changes be made? 
      description: Provide the links to the Upsun Flex and/or Upsun Fixed pages you think should be updated.
      placeholder: https://docs.upsun.com/ and/or https://fixed.docs.upsun.com 
    validations:
      required: true

  - type: textarea
    attributes:
      label: What exactly should be updated?
      description: |
        - Share as much detail as you can to help us understand the suggestion. 
        - What needs to be added, removed, or updated? 
        - What do you expect as an outcome?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: 'Optional: Add any other information or screenshots that could help us understand and implement the change.'
    validations:
      required: false
