name: New docs
description: For adding documentation that doesn't yet exist, such as for a new feature.
labels:
  - ungroomed
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the Upsun docs!
        Please fill in the fields below so we can understand what to document.

  - type: textarea
    attributes:
      label: What needs to be documented?
      description: |
        Describe in detail what is missing from the documentation.
        For new features, include information such as key use cases, benefits to the user, business problem solved, etc. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: 'Optional: Include other information or screenshots that could help us understand what to document.'
    validations:
      required: false
