name: redirections contract verification
description: Verifies that the redirections for our contract with console are still valid
inputs:
  environment-url:
    description: 'Pull Request Environment URL'
    required: true
  number_retries:
    description: 'The number of attempts we should make to contact the target environment URL. 1 second delay between attempt.'
    required: false
    default: '100'

####
#outputs:
####

runs:
  using: 'node20'
  main: index.js
