name = "Upsun Fixed Docs"
license = "CC-BY-SA-4.0"
licenselink = "https://github.com/platformsh/platformsh-docs/blob/main/docs/themes/psh-docs/LICENSE.md"
description = "A theme for the Upsun Fixed docs"
homepage = "http://example.com/"
min_version = "0.104.0"

[author]
  name = "Upsun"
  homepage = "https://upsun.com"
