name: Lint markdown
on:
  push:
    branches-ignore:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: docs/package-lock.json
    
    - name: Lint markdown
      run: |
        cd docs
        npm ci
        npm run lint:markdown
